workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      node: latest
      npm: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - sguy83078@gmail.com
